### ISSUE TITLE
Dodanie 2 stopniowej autentykacji przy odbiorze dziecka

### ISSUE THREAD

**Issue by jaugustyn02** [praca-inz-pjjj/frontend#28]
1. Zaprojektować prosty sposób wdrożenia 2 stopniowej autentykacji w procesie odbioru dziecka (należy wziąć pod uwagę co już mamy, a czego jeszcze brakuje)
2. Po uzgodnieniu na tle grupy, jak będzie wyglądać ta funkcjonalność, należy ją zaimplementować i przetestować)

**Comment by KubaBiz** [comment]
Warto wziąć pod uwagę tablicę z Miro gdzie to jest krok po kroku opisane, oraz potrzebę zmiany backendu razem z frontendem i mobile
